// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ultima.Models;

#nullable disable

namespace Ultima.Migrations
{
    [DbContext(typeof(BdGlampingFinalContext))]
    [Migration("20241209054542_UpdateClienteModel")]
    partial class UpdateClienteModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ultima.Models.Abono", b =>
                {
                    b.Property<int>("IdAbono")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAbono"));

                    b.Property<double?>("CantAbono")
                        .HasColumnType("float");

                    b.Property<bool?>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateOnly?>("FechaAbono")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdReserva")
                        .HasColumnType("int");

                    b.Property<double?>("Iva")
                        .HasColumnType("float")
                        .HasColumnName("IVA");

                    b.Property<double?>("Pendiente")
                        .HasColumnType("float");

                    b.Property<double?>("Porcentaje")
                        .HasColumnType("float");

                    b.Property<double>("SubTotal")
                        .HasColumnType("float");

                    b.Property<double?>("ValorDeuda")
                        .HasColumnType("float");

                    b.HasKey("IdAbono")
                        .HasName("PK__Abono__A4693DA717B60198");

                    b.HasIndex("IdReserva");

                    b.ToTable("Abono", (string)null);
                });

            modelBuilder.Entity("Ultima.Models.Cliente", b =>
                {
                    b.Property<int>("NroDocumento")
                        .HasColumnType("int");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoDocumento")
                        .HasColumnType("int");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("NroDocumento")
                        .HasName("PK__Clientes__CC62C91CB58EF0F1");

                    b.HasIndex("IdRol");

                    b.HasIndex("IdTipoDocumento");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Ultima.Models.DetalleReservaPaquete", b =>
                {
                    b.Property<int>("DetalleReservaPaquete1")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DetalleReservaPaquete");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetalleReservaPaquete1"));

                    b.Property<int?>("Cantidad")
                        .HasColumnType("int");

                    b.Property<double?>("Costo")
                        .HasColumnType("float");

                    b.Property<int?>("IdPaquete")
                        .HasColumnType("int");

                    b.Property<int?>("IdReserva")
                        .HasColumnType("int");

                    b.HasKey("DetalleReservaPaquete1")
                        .HasName("PK__DetalleR__2E8BFF25D36038AD");

                    b.HasIndex("IdPaquete");

                    b.HasIndex("IdReserva");

                    b.ToTable("DetalleReservaPaquete", (string)null);
                });

            modelBuilder.Entity("Ultima.Models.DetalleReservaServicio", b =>
                {
                    b.Property<int>("IdDetalleReservaServicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetalleReservaServicio"));

                    b.Property<int?>("Cantidad")
                        .HasColumnType("int");

                    b.Property<double?>("Costo")
                        .HasColumnType("float");

                    b.Property<int?>("IdReserva")
                        .HasColumnType("int");

                    b.Property<int?>("IdServicio")
                        .HasColumnType("int");

                    b.HasKey("IdDetalleReservaServicio")
                        .HasName("PK__DetalleR__D3D91A5ABFAB516A");

                    b.HasIndex("IdReserva");

                    b.HasIndex("IdServicio");

                    b.ToTable("DetalleReservaServicio", (string)null);
                });

            modelBuilder.Entity("Ultima.Models.EstadosReserva", b =>
                {
                    b.Property<int>("IdEstadoReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstadoReserva"));

                    b.Property<string>("NombreEstadoReserva")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.HasKey("IdEstadoReserva")
                        .HasName("PK__EstadosR__3E654CA8AC5B1510");

                    b.ToTable("EstadosReserva", (string)null);
                });

            modelBuilder.Entity("Ultima.Models.HabitacionMueble", b =>
                {
                    b.Property<int>("IdHabitacionMueble")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHabitacionMueble"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("IdHabitacion")
                        .HasColumnType("int");

                    b.Property<int>("IdMueble")
                        .HasColumnType("int");

                    b.HasKey("IdHabitacionMueble")
                        .HasName("PK__Habitaci__402E049D3966CCDF");

                    b.HasIndex("IdHabitacion");

                    b.HasIndex("IdMueble");

                    b.ToTable("HabitacionMueble", (string)null);
                });

            modelBuilder.Entity("Ultima.Models.Habitacione", b =>
                {
                    b.Property<int>("IdHabitacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHabitacion"));

                    b.Property<int?>("Cantidad")
                        .HasColumnType("int");

                    b.Property<decimal>("Costo")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateOnly>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdTipoHabitacion")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdHabitacion")
                        .HasName("PK__Habitaci__8BBBF90102DDD785");

                    b.HasIndex("IdTipoHabitacion");

                    b.ToTable("Habitaciones");
                });

            modelBuilder.Entity("Ultima.Models.ImagenAbono", b =>
                {
                    b.Property<int>("IdImagenAbono")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdImagenAbono"));

                    b.Property<int?>("IdAbono")
                        .HasColumnType("int");

                    b.Property<int?>("IdImagen")
                        .HasColumnType("int");

                    b.HasKey("IdImagenAbono")
                        .HasName("PK__ImagenAb__A40FAE5309D1F3BF");

                    b.HasIndex("IdAbono");

                    b.HasIndex("IdImagen");

                    b.ToTable("ImagenAbono", (string)null);
                });

            modelBuilder.Entity("Ultima.Models.ImagenHabitacion", b =>
                {
                    b.Property<int>("IdImagenHabi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdImagenHabi"));

                    b.Property<int>("IdHabitacion")
                        .HasColumnType("int");

                    b.Property<int>("IdImagen")
                        .HasColumnType("int");

                    b.HasKey("IdImagenHabi")
                        .HasName("PK__ImagenHa__5B5FF6AD92383AF0");

                    b.HasIndex("IdHabitacion");

                    b.HasIndex("IdImagen");

                    b.ToTable("ImagenHabitacion", (string)null);
                });

            modelBuilder.Entity("Ultima.Models.ImagenPaquete", b =>
                {
                    b.Property<int>("IdImagenPaque")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdImagenPaque"));

                    b.Property<int>("IdImagen")
                        .HasColumnType("int");

                    b.Property<int>("IdPaquete")
                        .HasColumnType("int");

                    b.HasKey("IdImagenPaque")
                        .HasName("PK__ImagenPa__AD53DF943757EF55");

                    b.HasIndex("IdImagen");

                    b.HasIndex("IdPaquete");

                    b.ToTable("ImagenPaquete", (string)null);
                });

            modelBuilder.Entity("Ultima.Models.ImagenServicio", b =>
                {
                    b.Property<int>("IdImagenServi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdImagenServi"));

                    b.Property<int>("IdImagen")
                        .HasColumnType("int");

                    b.Property<int>("IdServicio")
                        .HasColumnType("int");

                    b.HasKey("IdImagenServi")
                        .HasName("PK__ImagenSe__3C03784C1C47D76A");

                    b.HasIndex("IdImagen");

                    b.HasIndex("IdServicio");

                    b.ToTable("ImagenServicio", (string)null);
                });

            modelBuilder.Entity("Ultima.Models.Imagene", b =>
                {
                    b.Property<int>("IdImagen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdImagen"));

                    b.Property<string>("UrlImagen")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdImagen")
                        .HasName("PK__Imagenes__B42D8F2A3284391F");

                    b.ToTable("Imagenes");
                });

            modelBuilder.Entity("Ultima.Models.MetodoPago", b =>
                {
                    b.Property<int>("IdMetodoPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMetodoPago"));

                    b.Property<string>("NomMetodoPago")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("IdMetodoPago")
                        .HasName("PK__MetodoPa__6F49A9BE0163EA2A");

                    b.ToTable("MetodoPago", (string)null);
                });

            modelBuilder.Entity("Ultima.Models.Mueble", b =>
                {
                    b.Property<int>("IdMueble")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMueble"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateOnly>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<byte[]>("Imagen")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal?>("Valor")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("IdMueble")
                        .HasName("PK__Muebles__829D15E8CA56FBC7");

                    b.ToTable("Muebles");
                });

            modelBuilder.Entity("Ultima.Models.Paquete", b =>
                {
                    b.Property<int>("IdPaquete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPaquete"));

                    b.Property<decimal>("Costo")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("IdHabitacion")
                        .HasColumnType("int");

                    b.Property<string>("NomPaquete")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdPaquete")
                        .HasName("PK__Paquetes__DE278F8BD7FB8643");

                    b.HasIndex("IdHabitacion");

                    b.ToTable("Paquetes");
                });

            modelBuilder.Entity("Ultima.Models.PaqueteServicio", b =>
                {
                    b.Property<int>("IdPaqueteServicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPaqueteServicio"));

                    b.Property<decimal?>("Costo")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<int?>("IdPaquete")
                        .HasColumnType("int");

                    b.Property<int?>("IdServicio")
                        .HasColumnType("int");

                    b.HasKey("IdPaqueteServicio")
                        .HasName("PK__PaqueteS__DE5C2BC24D782718");

                    b.HasIndex("IdPaquete");

                    b.HasIndex("IdServicio");

                    b.ToTable("PaqueteServicio", (string)null);
                });

            modelBuilder.Entity("Ultima.Models.Permiso", b =>
                {
                    b.Property<int>("IdPermiso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPermiso"));

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("NomPermiso")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PermisosSeleccionados")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasDefaultValue("Sin permiso");

                    b.HasKey("IdPermiso")
                        .HasName("PK__Permisos__0D626EC87506DF0F");

                    b.ToTable("Permisos");
                });

            modelBuilder.Entity("Ultima.Models.PermisosRole", b =>
                {
                    b.Property<int>("IdPermisosRoles")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPermisosRoles"));

                    b.Property<int?>("IdPermiso")
                        .HasColumnType("int");

                    b.Property<int?>("IdRol")
                        .HasColumnType("int");

                    b.HasKey("IdPermisosRoles")
                        .HasName("PK__Permisos__8C257ED9F16A96CD");

                    b.HasIndex("IdPermiso");

                    b.HasIndex("IdRol");

                    b.ToTable("PermisosRoles");
                });

            modelBuilder.Entity("Ultima.Models.Reserva", b =>
                {
                    b.Property<int>("IdReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReserva"));

                    b.Property<double?>("Descuento")
                        .HasColumnType("float");

                    b.Property<DateTime>("FechaFinalizacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("FechaReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("IdEstadoReserva")
                        .HasColumnType("int");

                    b.Property<double?>("Iva")
                        .HasColumnType("float")
                        .HasColumnName("IVA");

                    b.Property<int>("MetodoPago")
                        .HasColumnType("int");

                    b.Property<double>("MontoTotal")
                        .HasColumnType("float");

                    b.Property<int>("NroDocumentoCliente")
                        .HasColumnType("int");

                    b.Property<int?>("NroDocumentoUsuario")
                        .HasColumnType("int");

                    b.Property<int?>("NroPersonas")
                        .HasColumnType("int");

                    b.Property<double?>("SubTotal")
                        .HasColumnType("float");

                    b.HasKey("IdReserva")
                        .HasName("PK__Reservas__0E49C69D3D983CC1");

                    b.HasIndex("IdEstadoReserva");

                    b.HasIndex("MetodoPago");

                    b.HasIndex("NroDocumentoCliente");

                    b.HasIndex("NroDocumentoUsuario");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("Ultima.Models.Role", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("NomRol")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("IdRol")
                        .HasName("PK__Roles__2A49584C4358CBA4");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Ultima.Models.Servicio", b =>
                {
                    b.Property<int>("IdServicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdServicio"));

                    b.Property<decimal>("Costo")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("IdTipoServicio")
                        .HasColumnType("int");

                    b.Property<string>("NomServicio")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdServicio")
                        .HasName("PK__Servicio__2DCCF9A24485B156");

                    b.HasIndex("IdTipoServicio");

                    b.ToTable("Servicios");
                });

            modelBuilder.Entity("Ultima.Models.TipoDocumento", b =>
                {
                    b.Property<int>("IdTipoDocumento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoDocumento"));

                    b.Property<string>("NomTipoDcumento")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdTipoDocumento")
                        .HasName("PK__TipoDocu__3AB3332F3F8876BE");

                    b.ToTable("TipoDocumento", (string)null);
                });

            modelBuilder.Entity("Ultima.Models.TipoHabitacione", b =>
                {
                    b.Property<int>("IdTipoHabitacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoHabitacion"));

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("NomTipoHabitacion")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("NumeroPersonas")
                        .HasColumnType("int");

                    b.HasKey("IdTipoHabitacion")
                        .HasName("PK__TipoHabi__AB75E87C4FADDF8A");

                    b.ToTable("TipoHabitaciones");
                });

            modelBuilder.Entity("Ultima.Models.TipoServicio", b =>
                {
                    b.Property<int>("IdTipoServicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoServicio"));

                    b.Property<string>("NombreTipoServicio")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdTipoServicio")
                        .HasName("PK__TipoServ__E29B3EA7DE3B5020");

                    b.ToTable("TipoServicios");
                });

            modelBuilder.Entity("Ultima.Models.Usuario", b =>
                {
                    b.Property<int>("NroDocumento")
                        .HasColumnType("int");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Contrasena")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.Property<int?>("IdTipoDocumento")
                        .HasColumnType("int");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TipoDocumento")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Tipo_Documento");

                    b.HasKey("NroDocumento")
                        .HasName("PK__Usuarios__CC62C91CD8DABF24");

                    b.HasIndex("IdRol");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Ultima.Models.Abono", b =>
                {
                    b.HasOne("Ultima.Models.Reserva", "oReserva")
                        .WithMany("Abonos")
                        .HasForeignKey("IdReserva")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Abono__IdReserva__04E4BC85");

                    b.Navigation("oReserva");
                });

            modelBuilder.Entity("Ultima.Models.Cliente", b =>
                {
                    b.HasOne("Ultima.Models.Role", "IdRolNavigation")
                        .WithMany("Clientes")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Clientes__IdRol__05D8E0BE");

                    b.HasOne("Ultima.Models.TipoDocumento", "oTipoDocumento")
                        .WithMany("Clientes")
                        .HasForeignKey("IdTipoDocumento")
                        .IsRequired()
                        .HasConstraintName("FK__Clientes__IdTipo__06CD04F7");

                    b.Navigation("IdRolNavigation");

                    b.Navigation("oTipoDocumento");
                });

            modelBuilder.Entity("Ultima.Models.DetalleReservaPaquete", b =>
                {
                    b.HasOne("Ultima.Models.Paquete", "oPaquete")
                        .WithMany("DetalleReservaPaquetes")
                        .HasForeignKey("IdPaquete")
                        .HasConstraintName("FK__DetalleRe__IdPaq__07C12930");

                    b.HasOne("Ultima.Models.Reserva", "oReserva")
                        .WithMany("DetalleReservaPaquetes")
                        .HasForeignKey("IdReserva")
                        .HasConstraintName("FK__DetalleRe__IdRes__08B54D69");

                    b.Navigation("oPaquete");

                    b.Navigation("oReserva");
                });

            modelBuilder.Entity("Ultima.Models.DetalleReservaServicio", b =>
                {
                    b.HasOne("Ultima.Models.Reserva", "oReserva")
                        .WithMany("DetalleReservaServicios")
                        .HasForeignKey("IdReserva")
                        .HasConstraintName("FK__DetalleRe__IdRes__09A971A2");

                    b.HasOne("Ultima.Models.Servicio", "oServicio")
                        .WithMany("DetalleReservaServicios")
                        .HasForeignKey("IdServicio")
                        .HasConstraintName("FK__DetalleRe__IdSer__0A9D95DB");

                    b.Navigation("oReserva");

                    b.Navigation("oServicio");
                });

            modelBuilder.Entity("Ultima.Models.HabitacionMueble", b =>
                {
                    b.HasOne("Ultima.Models.Habitacione", "IdHabitacionNavigation")
                        .WithMany("HabitacionMuebles")
                        .HasForeignKey("IdHabitacion")
                        .IsRequired()
                        .HasConstraintName("FK__Habitacio__IdHab__0C85DE4D");

                    b.HasOne("Ultima.Models.Mueble", "IdMuebleNavigation")
                        .WithMany("HabitacionMuebles")
                        .HasForeignKey("IdMueble")
                        .IsRequired()
                        .HasConstraintName("FK__Habitacio__IdMue__0D7A0286");

                    b.Navigation("IdHabitacionNavigation");

                    b.Navigation("IdMuebleNavigation");
                });

            modelBuilder.Entity("Ultima.Models.Habitacione", b =>
                {
                    b.HasOne("Ultima.Models.TipoHabitacione", "oTipoHabitacion")
                        .WithMany("Habitaciones")
                        .HasForeignKey("IdTipoHabitacion")
                        .IsRequired()
                        .HasConstraintName("FK__Habitacio__IdTip__0B91BA14");

                    b.Navigation("oTipoHabitacion");
                });

            modelBuilder.Entity("Ultima.Models.ImagenAbono", b =>
                {
                    b.HasOne("Ultima.Models.Abono", "oAbono")
                        .WithMany("ImagenAbonos")
                        .HasForeignKey("IdAbono")
                        .HasConstraintName("FK__ImagenAbo__IdAbo__0E6E26BF");

                    b.HasOne("Ultima.Models.Imagene", "oImagen")
                        .WithMany("ImagenAbonos")
                        .HasForeignKey("IdImagen")
                        .HasConstraintName("FK__ImagenAbo__IdIma__0F624AF8");

                    b.Navigation("oAbono");

                    b.Navigation("oImagen");
                });

            modelBuilder.Entity("Ultima.Models.ImagenHabitacion", b =>
                {
                    b.HasOne("Ultima.Models.Habitacione", "IdHabitacionNavigation")
                        .WithMany("ImagenHabitacions")
                        .HasForeignKey("IdHabitacion")
                        .IsRequired()
                        .HasConstraintName("FK__ImagenHab__IdHab__10566F31");

                    b.HasOne("Ultima.Models.Imagene", "IdImagenNavigation")
                        .WithMany("ImagenHabitacions")
                        .HasForeignKey("IdImagen")
                        .IsRequired()
                        .HasConstraintName("FK__ImagenHab__IdIma__114A936A");

                    b.Navigation("IdHabitacionNavigation");

                    b.Navigation("IdImagenNavigation");
                });

            modelBuilder.Entity("Ultima.Models.ImagenPaquete", b =>
                {
                    b.HasOne("Ultima.Models.Imagene", "IdImagenNavigation")
                        .WithMany("ImagenPaquetes")
                        .HasForeignKey("IdImagen")
                        .IsRequired()
                        .HasConstraintName("FK__ImagenPaq__IdIma__123EB7A3");

                    b.HasOne("Ultima.Models.Paquete", "IdPaqueteNavigation")
                        .WithMany("ImagenPaquetes")
                        .HasForeignKey("IdPaquete")
                        .IsRequired()
                        .HasConstraintName("FK__ImagenPaq__IdPaq__1332DBDC");

                    b.Navigation("IdImagenNavigation");

                    b.Navigation("IdPaqueteNavigation");
                });

            modelBuilder.Entity("Ultima.Models.ImagenServicio", b =>
                {
                    b.HasOne("Ultima.Models.Imagene", "IdImagenNavigation")
                        .WithMany("ImagenServicios")
                        .HasForeignKey("IdImagen")
                        .IsRequired()
                        .HasConstraintName("FK__ImagenSer__IdIma__14270015");

                    b.HasOne("Ultima.Models.Servicio", "IdServicioNavigation")
                        .WithMany("ImagenServicios")
                        .HasForeignKey("IdServicio")
                        .IsRequired()
                        .HasConstraintName("FK__ImagenSer__IdSer__151B244E");

                    b.Navigation("IdImagenNavigation");

                    b.Navigation("IdServicioNavigation");
                });

            modelBuilder.Entity("Ultima.Models.Paquete", b =>
                {
                    b.HasOne("Ultima.Models.Habitacione", "oHabitacion")
                        .WithMany("Paquetes")
                        .HasForeignKey("IdHabitacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Paquetes__IdHabi__160F4887");

                    b.Navigation("oHabitacion");
                });

            modelBuilder.Entity("Ultima.Models.PaqueteServicio", b =>
                {
                    b.HasOne("Ultima.Models.Paquete", "oPaquete")
                        .WithMany("PaqueteServicios")
                        .HasForeignKey("IdPaquete")
                        .HasConstraintName("FK__PaqueteSe__IdPaq__17036CC0");

                    b.HasOne("Ultima.Models.Servicio", "oServicio")
                        .WithMany("PaqueteServicios")
                        .HasForeignKey("IdServicio")
                        .HasConstraintName("FK__PaqueteSe__IdSer__17F790F9");

                    b.Navigation("oPaquete");

                    b.Navigation("oServicio");
                });

            modelBuilder.Entity("Ultima.Models.PermisosRole", b =>
                {
                    b.HasOne("Ultima.Models.Permiso", "IdPermisoNavigation")
                        .WithMany("PermisosRoles")
                        .HasForeignKey("IdPermiso")
                        .HasConstraintName("FK__PermisosR__IdPer__18EBB532");

                    b.HasOne("Ultima.Models.Role", "IdRolNavigation")
                        .WithMany("PermisosRoles")
                        .HasForeignKey("IdRol")
                        .HasConstraintName("FK__PermisosR__IdRol__19DFD96B");

                    b.Navigation("IdPermisoNavigation");

                    b.Navigation("IdRolNavigation");
                });

            modelBuilder.Entity("Ultima.Models.Reserva", b =>
                {
                    b.HasOne("Ultima.Models.EstadosReserva", "oEstadoReserva")
                        .WithMany("Reservas")
                        .HasForeignKey("IdEstadoReserva")
                        .HasConstraintName("FK__Reservas__IdEsta__1AD3FDA4");

                    b.HasOne("Ultima.Models.MetodoPago", "oMetodoPago")
                        .WithMany("Reservas")
                        .HasForeignKey("MetodoPago")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Reservas__Metodo__1BC821DD");

                    b.HasOne("Ultima.Models.Cliente", "oCliente")
                        .WithMany("Reservas")
                        .HasForeignKey("NroDocumentoCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Reservas__NroDoc__1CBC4616");

                    b.HasOne("Ultima.Models.Usuario", "oUsuario")
                        .WithMany("Reservas")
                        .HasForeignKey("NroDocumentoUsuario")
                        .HasConstraintName("FK__Reservas__NroDoc__1DB06A4F");

                    b.Navigation("oCliente");

                    b.Navigation("oEstadoReserva");

                    b.Navigation("oMetodoPago");

                    b.Navigation("oUsuario");
                });

            modelBuilder.Entity("Ultima.Models.Servicio", b =>
                {
                    b.HasOne("Ultima.Models.TipoServicio", "oTipoServicio")
                        .WithMany("Servicios")
                        .HasForeignKey("IdTipoServicio")
                        .IsRequired()
                        .HasConstraintName("FK__Servicios__IdTip__1EA48E88");

                    b.Navigation("oTipoServicio");
                });

            modelBuilder.Entity("Ultima.Models.Usuario", b =>
                {
                    b.HasOne("Ultima.Models.Role", "IdRolNavigation")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Usuarios__IdRol__1F98B2C1");

                    b.Navigation("IdRolNavigation");
                });

            modelBuilder.Entity("Ultima.Models.Abono", b =>
                {
                    b.Navigation("ImagenAbonos");
                });

            modelBuilder.Entity("Ultima.Models.Cliente", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("Ultima.Models.EstadosReserva", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("Ultima.Models.Habitacione", b =>
                {
                    b.Navigation("HabitacionMuebles");

                    b.Navigation("ImagenHabitacions");

                    b.Navigation("Paquetes");
                });

            modelBuilder.Entity("Ultima.Models.Imagene", b =>
                {
                    b.Navigation("ImagenAbonos");

                    b.Navigation("ImagenHabitacions");

                    b.Navigation("ImagenPaquetes");

                    b.Navigation("ImagenServicios");
                });

            modelBuilder.Entity("Ultima.Models.MetodoPago", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("Ultima.Models.Mueble", b =>
                {
                    b.Navigation("HabitacionMuebles");
                });

            modelBuilder.Entity("Ultima.Models.Paquete", b =>
                {
                    b.Navigation("DetalleReservaPaquetes");

                    b.Navigation("ImagenPaquetes");

                    b.Navigation("PaqueteServicios");
                });

            modelBuilder.Entity("Ultima.Models.Permiso", b =>
                {
                    b.Navigation("PermisosRoles");
                });

            modelBuilder.Entity("Ultima.Models.Reserva", b =>
                {
                    b.Navigation("Abonos");

                    b.Navigation("DetalleReservaPaquetes");

                    b.Navigation("DetalleReservaServicios");
                });

            modelBuilder.Entity("Ultima.Models.Role", b =>
                {
                    b.Navigation("Clientes");

                    b.Navigation("PermisosRoles");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Ultima.Models.Servicio", b =>
                {
                    b.Navigation("DetalleReservaServicios");

                    b.Navigation("ImagenServicios");

                    b.Navigation("PaqueteServicios");
                });

            modelBuilder.Entity("Ultima.Models.TipoDocumento", b =>
                {
                    b.Navigation("Clientes");
                });

            modelBuilder.Entity("Ultima.Models.TipoHabitacione", b =>
                {
                    b.Navigation("Habitaciones");
                });

            modelBuilder.Entity("Ultima.Models.TipoServicio", b =>
                {
                    b.Navigation("Servicios");
                });

            modelBuilder.Entity("Ultima.Models.Usuario", b =>
                {
                    b.Navigation("Reservas");
                });
#pragma warning restore 612, 618
        }
    }
}
